package:
  name: q2-kmerizer
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - pip
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - numpy {{ numpy }}
  - pandas {{ pandas }}
  - scikit-bio {{ scikit_bio }}
  - scikit-learn {{ scikit_learn }}
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - q2-feature-table >={{ q2_feature_table }}
  - pytest
  imports:
  - q2_kmerizer
  - qiime2.plugins.kmerizer
  commands:
  - py.test --pyargs q2_kmerizer
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
